"""Hexagon bundles indexed by graphs.  Vertices c = base factors P^{b_c}; edges i = hexagons (dP_6):
hexagon i joins plus_i and minus_i and is twisted by +r_i along the ray f^c_0 of P^{b_c}, c = plus_i,
and by -r_i along f^c_0, c = minus_i (the orientation is immaterial: -1 on the hexagon reverses it).
X(G) is the (dP_6)^j-bundle over prod_c P^{b_c};  n = 2j + sum b_c,  rho - n = 2j + k - sum b_c.

Fano: the primitive relations are those of the hexagons and f^c_0+...+f^c_{b_c} = (sum of the
twists at c), of degree b_c + 1 - deg(c); so X(G) is Fano iff deg(c) <= b_c for every c.
The ray matroid is connected iff G is connected.  For a tree with b_c = deg(c) ("saturated"):
n = 4j and rho - n = j + 1.  The star with j edges is X_j(j) of xjb_family.py; paths use only
P^1 and P^2.

Degrees.  With a_i = <m_i, r_i>, s_c = sum_{plus_i=c} a_i - sum_{minus_i=c} a_i, L_c = b_c+1+s_c,
the slice of the moment polytope over (m_i) is a product of simplices of sizes L_c:
    D = n! int prod_c L_c^{b_c}/b_c!,      d(f^c_t) = (n-1)! int (b_c/L_c) prod ...,
    d(h in hexagon i) = (n-1)! int prod ... with the a_i-measure replaced by that of the edge of h,
all against prod (2-|a_i|) da_i.  Evaluated exactly by polynomial expansion.

Stability: symmetry reduction (notes/theory.md Prop. 2.5) with the group generated by the hexagon
reflections fixing r_i, the permutations of f^c_1..f^c_{b_c}, and the graph automorphisms; the
invariant ray-spanned subspaces are enumerated as closed unions of ray orbits.
Usage: tree_family.py            (validation against xjb_family + the table of trees)"""
import sys, os, time, math
from fractions import Fraction as Fr
from itertools import permutations
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, '..', '..', 'src'))
from toric_stability import rref, in_span
HEX = [(1,0),(0,1),(1,1),(-1,0),(0,-1),(-1,-1)]
KIND = {(1,0): 'r', (-1,0): '-r', (1,1): 'neg', (0,-1): 'neg', (0,1): 'pos', (-1,-1): 'pos'}

# ---------------------------------------------------------------- the variety
class HexGraph:
    def __init__(self, dims, edges, name=''):
        self.b = list(dims); self.edges = [tuple(e) for e in edges]; self.name = name
        self.j, self.k = len(edges), len(dims); self.n = 2*self.j + sum(dims)
        self.off = [2*self.j + sum(dims[:c]) for c in range(self.k)]
        deg = [sum(c in e for e in self.edges) for c in range(self.k)]
        assert all(p != m for p, m in self.edges)
        self.fano = all(deg[c] <= self.b[c] for c in range(self.k))
        self.rays, self.label = [], []
        for i in range(self.j):
            for h in HEX:
                v = [0]*self.n; v[2*i], v[2*i+1] = h
                self.rays.append(tuple(v)); self.label.append(('hex', i, h))
        for c in range(self.k):
            for t in range(self.b[c]):
                v = [0]*self.n; v[self.off[c]+t] = 1
                self.rays.append(tuple(v)); self.label.append(('base', c, t+1))
            v = [0]*self.n
            for t in range(self.b[c]): v[self.off[c]+t] = -1
            for i, (p, m) in enumerate(self.edges):
                if p == c: v[2*i] += 1
                if m == c: v[2*i] -= 1
            self.rays.append(tuple(v)); self.label.append(('base', c, 0))

    # ------------------------------------------------------------ degrees
    def _poly(self, drop=None):
        """prod_c L_c^{b_c}/b_c!, with the factor of base `drop` replaced by L^{b-1}/(b-1)!."""
        P = {(0,)*self.j: Fr(1)}
        for c in range(self.k):
            lin = {}
            for i, (p, m) in enumerate(self.edges):
                if p == c: lin[i] = lin.get(i, 0) + 1
                if m == c: lin[i] = lin.get(i, 0) - 1
            power = self.b[c] - (1 if c == drop else 0)
            for _ in range(power):
                Q = {}
                for mono, co in P.items():
                    Q[mono] = Q.get(mono, 0) + co*(self.b[c]+1)
                    for i, s in lin.items():
                        mm = mono[:i] + (mono[i]+1,) + mono[i+1:]
                        Q[mm] = Q.get(mm, 0) + co*s
                P = Q
            P = {mo: co / math.factorial(power) for mo, co in P.items() if co}
        return P

    @staticmethod
    def _moment(kind, q):
        if kind == 'bulk': return Fr(0) if q % 2 else 2*(Fr(2, q+1) - Fr(1, q+2))
        if kind == 'r':    return Fr((-1)**q)
        if kind == '-r':   return Fr(1)
        if kind == 'neg':  return Fr((-1)**q, q+1)
        if kind == 'pos':  return Fr(1, q+1)

    def _integrate(self, P, special=None):
        """special = (i, kind): hexagon i carries the edge measure `kind` instead of the bulk."""
        tot = Fr(0)
        for mono, co in P.items():
            term = co
            for i, q in enumerate(mono):
                mq = self._moment(special[1] if special and special[0] == i else 'bulk', q)
                if mq == 0: term = 0; break
                term *= mq
            tot += term
        return tot

    def degrees(self):
        P = self._poly(); fn1 = math.factorial(self.n - 1)
        D = self.n * fn1 * self._integrate(P)
        dh = {(i, kd): fn1 * self._integrate(P, (i, kd)) for i in range(self.j) for kd in ('r', '-r', 'neg', 'pos')}
        db = [fn1 * self._integrate(self._poly(drop=c)) for c in range(self.k)]
        deg = [dh[(l[1], KIND[l[2]])] if l[0] == 'hex' else db[l[1]] for l in self.label]
        assert sum(deg) == D, (sum(deg), D)
        return deg, D

    # ------------------------------------------------------------ symmetry
    def generators(self):
        n, gens = self.n, []
        for i in range(self.j):
            def refl(v, i=i):
                w = list(v); w[2*i], w[2*i+1] = v[2*i] - v[2*i+1], -v[2*i+1]; return tuple(w)
            gens.append(refl)
        for c in range(self.k):
            for t in range(self.b[c]-1):
                def sw(v, a=self.off[c]+t):
                    w = list(v); w[a], w[a+1] = w[a+1], w[a]; return tuple(w)
                gens.append(sw)
        und = [frozenset(e) for e in self.edges]
        if len(set(und)) == len(und) and self.k <= 9:            # simple graph: automorphisms by brute force
            for pi in permutations(range(self.k)):
                if pi == tuple(range(self.k)) or any(self.b[pi[c]] != self.b[c] for c in range(self.k)): continue
                img = [frozenset(pi[c] for c in e) for e in und]
                if set(img) != set(und): continue
                hp = [und.index(im) for im in img]
                eta = [1 if self.edges[hp[i]] == (pi[self.edges[i][0]], pi[self.edges[i][1]]) else -1 for i in range(self.j)]
                def auto(v, pi=pi, hp=hp, eta=eta):
                    w = [0]*n
                    for i in range(self.j):
                        w[2*hp[i]], w[2*hp[i]+1] = eta[i]*v[2*i], eta[i]*v[2*i+1]
                    for c in range(self.k):
                        for t in range(self.b[c]): w[self.off[pi[c]]+t] = v[self.off[c]+t]
                    return tuple(w)
                gens.append(auto)
        return gens

    def orbits(self):
        idx = {v: q for q, v in enumerate(self.rays)}; parent = list(range(len(self.rays)))
        def find(x):
            while parent[x] != x: parent[x] = parent[parent[x]]; x = parent[x]
            return x
        for g in self.generators():
            for q, v in enumerate(self.rays):
                assert g(v) in idx, "generator does not preserve the ray set"
                parent[find(q)] = find(idx[g(v)])
        orbs = {}
        for q in range(len(self.rays)): orbs.setdefault(find(q), []).append(q)
        return list(orbs.values())

    def verdict(self, max_states=200000):
        deg, D = self.degrees(); mu = D / self.n; orbs = self.orbits(); R = self.rays
        def close(basis_rows, add):
            rk, canon = rref(list(basis_rows) + [R[q] for q in orbs[add]])
            inside = frozenset(o for o in range(len(orbs)) if in_span(canon, R[orbs[o][0]]))
            return rk, canon, inside
        states = {}; frontier = []
        for o in range(len(orbs)):
            rk, canon, inside = close([], o)
            if inside not in states: states[inside] = (rk, canon); frontier.append(inside)
        while frontier:
            S = frontier.pop(); rk, canon = states[S]
            if rk == self.n: continue
            for o in range(len(orbs)):
                if o in S: continue
                rk2, canon2, S2 = close(canon, o)
                if S2 not in states:
                    states[S2] = (rk2, canon2); frontier.append(S2)
                    if len(states) > max_states: raise RuntimeError("too many invariant flats")
        # margin(V) = dim V - (sum of d_v over rays in V)/mu: the slack of the Klyachko inequality in
        # units of mu.  Stable iff every margin is > 0.  (The ratio slope/mu tends to 1 for any family
        # of subspaces of bounded codimension as n grows, so the margin is the quantity to follow.)
        flats = []
        for S, (rk, canon) in states.items():
            if rk == self.n: continue
            w = sum(deg[q] for o in S for q in orbs[o])
            flats.append((rk - w/mu, w/rk, rk, S))
        flats.sort(key=lambda f: f[0])
        def describe(S):
            inside = [self.label[q] for o in S for q in orbs[o]]
            hexfull = sorted({l[1] for l in inside if l[0] == 'hex' and sum(1 for x in inside if x[:2] == l[:2]) == 6})
            basefull = sorted({l[1] for l in inside if l[0] == 'base' and sum(1 for x in inside if x[:2] == l[:2]) == self.b[l[1]]+1})
            other = sorted(l for l in inside if not (l[0] == 'hex' and l[1] in hexfull) and not (l[0] == 'base' and l[1] in basefull))
            return hexfull, basefull, other
        slope, rk, S = max(((f[1], f[2], f[3]) for f in flats), key=lambda t: t[0])
        hexfull, basefull, other = describe(S)
        mmin = flats[0][0]
        v = 'stable' if mmin > 0 else ('not stable (equality)' if mmin == 0 else 'unstable')
        assert (slope < mu) == (mmin > 0)
        return dict(verdict=v, ratio=slope/mu, mu=mu, D=D, max_inv_slope=slope, dim=rk, n_orbits=len(orbs),
                    n_flats=len(states), hexagons=hexfull, bases=basefull, other=other, min_margin=mmin,
                    tightest=[(f[0], f[2]) + describe(f[3]) for f in flats[:8]])

# ---------------------------------------------------------------- families
def star(j, b):      return HexGraph([1]*j + [b], [(i, j) for i in range(j)], f"star X_{j}({b})")
def path(j):         return HexGraph([1] + [2]*(j-1) + [1], [(i+1, i) for i in range(j)], f"path, {j} hexagons")
def spider(*legs):
    """A central vertex with legs of the given lengths (in hexagons); saturated."""
    dims, edges = [len(legs)], []
    for L in legs:
        prev = 0
        for s in range(L):
            dims.append(1 if s == L-1 else 2); edges.append((len(dims)-1, prev)); prev = len(dims)-1
    return HexGraph(dims, edges, f"spider{legs}")

def report(G):
    t0 = time.time()
    if not G.fano: print(f"{G.name}: not Fano", flush=True); return
    r = G.verdict(); m, dim, hx, bs, other = r['tightest'][0]
    print(f"{G.name:<22s} n={G.n:3d} rho=n{len(G.rays)-2*G.n:+d}  {r['verdict']:<21s} min margin {float(r['min_margin']):+.5f}  "
          f"(tightest: dim {dim}, hexagons {hx}, bases {bs}" + (f", other {other}" if other else '') + f")  max slope/mu {float(r['ratio']):.6f}"
          + f"   [{r['n_orbits']} orbits, {r['n_flats']} invariant flats, {time.time()-t0:.0f}s]", flush=True)
    return r

if __name__ == '__main__':
    print("== validation: stars against xjb_family (closed form in one variable)", flush=True)
    import xjb_family as X
    for j, b in [(1,1), (2,2), (2,3), (3,3), (1,4), (3,4)]:
        G = star(j, b); deg, D = G.degrees(); deg2, D2 = X.closed_form(j, b)
        r = G.verdict(); s = X.symmetry_verdict(j, b)
        # X_1(1) has an extra automorphism as a graph (the two P^1's are exchanged), hence fewer invariant
        # subspaces; the maximal invariant slope is comparable only when the two groups coincide.
        same_group = (j, b) != (1, 1)
        ok = D == D2 and sorted(deg) == sorted(deg2) and r['verdict'] == s['verdict'] and (not same_group or r['max_inv_slope'] == s['max_inv_slope'])
        print(f"  X_{j}({b}): D = {D}, {r['verdict']}, ratio {float(r['ratio']):.6f} (xjb: {float(s['max_inv_slope']/s['mu']):.6f}); agrees: {ok}", flush=True)
        assert ok
    print("\n== validation: a non-star graph against the general exact checker (dim 8)", flush=True)
    sys.path.insert(0, HERE)
    import toric_fast as tf
    from screen_high_rank import degrees as general_degrees
    G = HexGraph([2, 2], [(0, 1), (1, 0)], "2-cycle on P^2, P^2")
    deg, D = G.degrees(); gdeg, gD, _ = general_degrees(G.rays); r = G.verdict()
    res = tf.analyze_fast(G.rays, name=G.name); gs = Fr(*res['max_subsheaf_slope'])
    ok = [Fr(x) for x in gdeg] == deg and Fr(gD) == D and res['verdict'] == r['verdict'] and gs == r['max_inv_slope']
    print(f"  {G.name}: n = {G.n}, rho = n{len(G.rays)-2*G.n:+d}, D = {D}; general checker: {res['verdict']}, max slope {gs}; "
          f"symmetry reduction: {r['verdict']}, max invariant slope {r['max_inv_slope']}; degrees, verdict and slope agree: {ok}", flush=True)
    assert ok
    print("\n== trees (saturated: b_c = deg(c), n = 4j, rho = n + j + 1)", flush=True)
    for G in [path(1), path(2), path(3), star(3,3), path(4), spider(1,1,2), path(5), spider(1,2,2), spider(2,2,2), path(6), path(7)]:
        report(G)
