#!/usr/bin/env python3
"""Klyachko slope checker: (semi)stability of the tangent bundle of a smooth
toric Fano variety with respect to the anticanonical polarization.

Input per variety: the primitive ray generators of the fan = the vertices of
the smooth Fano polytope Q in N (facets of Q are unimodular simplices).

Method
------
Let P = Q^* in M be the dual reflexive polytope (the moment polytope of -K).

  deg_{-K}(D_rho) = normalized lattice volume of the facet
                    F_rho = { m in P : <m, u_rho> = -1 }.

Klyachko data of T_X:  E = N_C, and for each ray rho the decreasing filtration
  E^rho(j) = E for j <= 0,  C.u_rho for j = 1,  0 for j >= 2.

The saturated equivariant subsheaf generated by a subspace V of N_C has
filtrations (V intersect E^rho(j)), hence

  deg_{-K}(V) = sum_{rho : u_rho in V} deg_{-K}(D_rho),   mu(V) = deg/dim V.

Reductions (standard; cf. Klyachko, Kool, Hering--Nill--Suess):
  * the equivariant stability criterion for toric sheaves reduces both the
    strict and weak slope inequalities to equivariant subsheaves (HN
    uniqueness handles instability; the equality boundary uses the
    equivariant socle/fixed-point argument);
  * replacing V by the span of the rays it contains keeps the degree and can
    only drop the dimension, so it suffices to test V = span of an independent
    subset of ray generators, 1 <= dim V <= n-1.

Verdicts: 'stable' (all mu(V) < mu(T_X)), 'strictly semistable' (max attains
equality), 'unstable' (some mu(V) exceeds).  Also reports the barycenter of P:
by Wang--Zhu, X admits a Kahler--Einstein metric iff the barycenter is 0.

Everything is exact integer/rational arithmetic.
"""

from fractions import Fraction as Fr
from itertools import combinations
import json
import math
import os
import sys

# ---------------------------------------------------------------- linear algebra


def egcd(a, b):
    """g, x, y with a*x + b*y = g >= 0."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def rref(rows):
    """Reduced row echelon form over Q; returns (rank, canonical tuple)."""
    m = [[Fr(x) for x in row] for row in rows]
    nrows, ncols = len(m), len(m[0])
    r = 0
    for c in range(ncols):
        piv = next((i for i in range(r, nrows) if m[i][c] != 0), None)
        if piv is None:
            continue
        m[r], m[piv] = m[piv], m[r]
        inv = m[r][c]
        m[r] = [v / inv for v in m[r]]
        for i in range(nrows):
            if i != r and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b for a, b in zip(m[i], m[r])]
        r += 1
        if r == nrows:
            break
    canon = tuple(tuple(row) for row in m[:r])
    return r, canon


def rank(rows):
    return rref(rows)[0]


def in_span(rref_rows, vec):
    """Is vec in the row span of an rref basis?  (Reduce and test zero.)"""
    v = [Fr(x) for x in vec]
    for row in rref_rows:
        p = next(j for j, val in enumerate(row) if val != 0)
        if v[p] != 0:
            f = v[p]                       # rref pivots are 1
            v = [a - f * b for a, b in zip(v, row)]
    return all(x == 0 for x in v)


def solve_square(A, b):
    """Solve A x = b exactly; None if singular."""
    n = len(A)
    m = [[Fr(A[i][j]) for j in range(n)] + [Fr(b[i])] for i in range(n)]
    for c in range(n):
        piv = next((i for i in range(c, n) if m[i][c] != 0), None)
        if piv is None:
            return None
        m[c], m[piv] = m[piv], m[c]
        inv = m[c][c]
        m[c] = [v / inv for v in m[c]]
        for i in range(n):
            if i != c and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b_ for a, b_ in zip(m[i], m[c])]
    return [m[i][n] for i in range(n)]


def det(rows):
    n = len(rows)
    if n == 0:
        return Fr(1)
    if all(isinstance(x, int) for row in rows for x in row):
        # fraction-free Bareiss on the integer fast path
        m = [list(r) for r in rows]
        sign, prev = 1, 1
        for k in range(n - 1):
            if m[k][k] == 0:
                piv = next((i for i in range(k + 1, n) if m[i][k] != 0), None)
                if piv is None:
                    return Fr(0)
                m[k], m[piv] = m[piv], m[k]
                sign = -sign
            for i in range(k + 1, n):
                for j in range(k + 1, n):
                    m[i][j] = (m[i][j] * m[k][k] - m[i][k] * m[k][j]) // prev
                m[i][k] = 0
            prev = m[k][k]
        return Fr(sign * m[n - 1][n - 1])
    m = [[Fr(x) for x in row] for row in rows]
    d = Fr(1)
    for c in range(n):
        piv = next((i for i in range(c, n) if m[i][c] != 0), None)
        if piv is None:
            return Fr(0)
        if piv != c:
            m[c], m[piv] = m[piv], m[c]
            d = -d
        d *= m[c][c]
        inv = m[c][c]
        for i in range(c + 1, n):
            if m[i][c] != 0:
                f = m[i][c] / inv
                m[i] = [a - f * b for a, b in zip(m[i], m[c])]
    return d


def mat_inverse(rows):
    n = len(rows)
    m = [[Fr(rows[i][j]) for j in range(n)] + [Fr(1) if i == j else Fr(0) for j in range(n)]
         for i in range(n)]
    for c in range(n):
        piv = next((i for i in range(c, n) if m[i][c] != 0), None)
        assert piv is not None, "singular matrix"
        m[c], m[piv] = m[piv], m[c]
        inv = m[c][c]
        m[c] = [v / inv for v in m[c]]
        for i in range(n):
            if i != c and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b for a, b in zip(m[i], m[c])]
    return [row[n:] for row in m]


def unimodular_completion(u):
    """Integer n x n matrix V (list of columns) with u . V = (1, 0, ..., 0).

    Columns 1..n-1 of V are then a lattice basis of ker<., u>, and column 0 is
    a vector pairing to 1 with u.  Requires u primitive.
    """
    n = len(u)
    cols = [[1 if i == j else 0 for i in range(n)] for j in range(n)]
    w = list(u)
    for i in range(1, n):
        a, b = w[0], w[i]
        if b == 0:
            continue
        g, x, y = egcd(a, b)
        c0, ci = cols[0], cols[i]
        cols[0] = [x * c0[k] + y * ci[k] for k in range(n)]
        cols[i] = [-(b // g) * c0[k] + (a // g) * ci[k] for k in range(n)]
        w[0], w[i] = g, 0
    assert abs(w[0]) == 1, f"ray {u} is not primitive"
    if w[0] == -1:
        cols[0] = [-v for v in cols[0]]
    return cols


# ---------------------------------------------------------------- polytope side


def dual_polytope_vertices(rays):
    """Vertices of P = { m : <m, u> >= -1 for all rays u }.  Exact; asserts
    that P is a lattice polytope (reflexivity of the input)."""
    n = len(rays[0])
    verts = set()
    for comb in combinations(rays, n):
        sol = solve_square(list(comb), [-1] * n)
        if sol is None:
            continue
        if all(dot(sol, u) >= -1 for u in rays):
            assert all(x.denominator == 1 for x in sol), \
                f"dual vertex {sol} not integral -- input not reflexive?"
            verts.add(tuple(int(x) for x in sol))
    return sorted(verts)


def facet_lattice_coords(u, facet_verts):
    """Coordinates of the facet's vertices in a lattice basis of the affine
    hyperplane <m, u> = -1 (dimension n-1)."""
    V = unimodular_completion(u)          # columns
    n = len(u)
    Vrows = [[V[c][r] for c in range(n)] for r in range(n)]  # row-major matrix
    Vinv = mat_inverse(Vrows)
    base = facet_verts[0]
    coords = []
    for m in facet_verts:
        d = [m[k] - base[k] for k in range(n)]
        y = [sum(Vinv[i][k] * d[k] for k in range(n)) for i in range(n)]
        assert y[0] == 0
        assert all(t.denominator == 1 for t in y)
        coords.append(tuple(int(t) for t in y[1:]))
    return coords


def primitive(vec):
    from math import gcd
    g = 0
    for x in vec:
        g = gcd(g, abs(x))
    assert g > 0
    return tuple(x // g for x in vec)


def hyperplane_through(pts):
    """Primitive integer (a, c) with <a, p> = c for all p, or None if the
    points are affinely dependent.  a is the generalized cross product."""
    d = len(pts[0])
    rows = [[pts[i][k] - pts[0][k] for k in range(d)] for i in range(1, d)]
    a = []
    for j in range(d):
        minor = [[row[k] for k in range(d) if k != j] for row in rows]
        a.append((-1) ** j * int(det(minor)))
    if all(x == 0 for x in a):
        return None
    a = primitive(a)
    return a, dot(a, pts[0])


def hull_facets(points):
    """Facets of conv(points) for full-dimensional points in Z^d.
    Returns list of (outward_normal, offset, facet_points)."""
    d = len(points[0])
    seen = {}
    for comb in combinations(range(len(points)), d):
        h = hyperplane_through([points[i] for i in comb])
        if h is None:
            continue
        a, c = h
        vals = [dot(a, p) for p in points]
        if max(vals) <= c:
            a, c, vals = tuple(-x for x in a), -c, [-v for v in vals]
        elif min(vals) < c:
            continue                                   # not supporting
        key = (a, c)
        if key not in seen:
            seen[key] = [p for p, v in zip(points, vals) if v == c]
    return [(a, c, fp) for (a, c), fp in seen.items()]


def triangulate_polytope(points):
    """Exact triangulation of a full-dimensional lattice polytope in Z^d into
    d-simplices on its vertices: recurse on facets, cone from points[0]."""
    d = len(points[0])
    if d == 1:
        lo = min(points)
        hi = max(points)
        return [(lo, hi)]
    if len(points) == d + 1:
        return [tuple(points)]
    v0 = points[0]
    simplices = []
    for a, c, fpts in hull_facets(points):
        if dot(a, v0) == c:
            continue                                   # v0 lies on this facet
        coords, lift = _to_lattice_coords(a, fpts)
        for s in triangulate_polytope(coords):
            simplices.append((v0,) + tuple(lift[p] for p in s))
    return simplices


def _to_lattice_coords(a, pts):
    """Coordinates of pts (all on <x,a> = const, a primitive) in a lattice
    basis of the hyperplane direction; returns (coords, lift dict)."""
    n = len(a)
    V = unimodular_completion(a)
    Vrows = [[V[c][r] for c in range(n)] for r in range(n)]
    Vinv = mat_inverse(Vrows)
    base = pts[0]
    coords, lift = [], {}
    for p in pts:
        dvec = [p[k] - base[k] for k in range(n)]
        y = [sum(Vinv[i][k] * dvec[k] for k in range(n)) for i in range(n)]
        assert y[0] == 0 and all(t.denominator == 1 for t in y)
        cc = tuple(int(t) for t in y[1:])
        coords.append(cc)
        lift[cc] = p
    return coords, lift


def normalized_volume(points):
    """d! * euclidean volume of conv(points), points full-dim in Z^d."""
    if len(points[0]) == 0:
        return 1
    total = 0
    for s in triangulate_polytope(points):
        edges = [[s[i][k] - s[0][k] for k in range(len(s[0]))]
                 for i in range(1, len(s))]
        total += abs(int(det(edges)))
    return total


def facet_normalized_volume(u, facet_verts):
    """(n-1)! * lattice volume of the facet with normal u."""
    coords = facet_lattice_coords(u, facet_verts)
    return normalized_volume(coords)


def facet_volume_and_triangulation(u, facet_verts):
    """Normalized volume of the facet AND its triangulation lifted back to the
    original M coordinates (computed once, reused for the barycenter)."""
    coords, lift = _to_lattice_coords(u, facet_verts)
    vol = 0
    lifted = []
    d = len(coords[0])
    for s in triangulate_polytope(coords):
        if d > 0:
            edges = [[s[i][k] - s[0][k] for k in range(d)]
                     for i in range(1, len(s))]
            vol += abs(int(det(edges)))
        else:
            vol += 1
        lifted.append(tuple(lift[p] for p in s))
    return vol, lifted


def barycenter_and_volume_from_facets(n, facet_triangulations):
    """Exact barycenter and euclidean volume of P from the already-computed
    facet triangulations, coning each facet simplex to the origin (0 is
    interior since P is reflexive)."""
    total = Fr(0)
    weighted = [Fr(0)] * n
    for tris in facet_triangulations:
        for s in tris:                      # s: n points spanning a facet simplex
            vol = abs(det(list(s))) / math.factorial(n)   # apex at 0
            cent = [sum(Fr(p[k]) for p in s) / (n + 1) for k in range(n)]
            total += vol
            for k in range(n):
                weighted[k] += vol * cent[k]
    return [w / total for w in weighted], total


# ---------------------------------------------------------------- stability


def analyze(rays, name=""):
    """Full stability analysis of T_X w.r.t. -K_X for the smooth toric variety
    with the given ray generators."""
    n = len(rays[0])
    r = len(rays)
    dual_verts = dual_polytope_vertices(rays)
    deg = []
    facet_tris = []
    for u in rays:
        fverts = [m for m in dual_verts if dot(m, u) == -1]
        assert len(fverts) >= n, f"ray {u}: facet has too few vertices"
        v, tris = facet_volume_and_triangulation(u, fverts)
        deg.append(v)
        facet_tris.append(tris)
    total = sum(deg)
    mu = Fr(total, n)

    bary, vol = barycenter_and_volume_from_facets(n, facet_tris)
    # consistency: sum_rho deg(D_rho) = (-K)^n = n! vol(P)
    assert total == math.factorial(n) * vol, (name, total, vol)

    seen = set()
    worst = (Fr(-1), None)          # (slope, description)
    top_canons = []
    equalities = []
    for k in range(1, n):
        for comb in combinations(range(r), k):
            rows = [rays[i] for i in comb]
            rk, canon = rref(rows)
            if rk < k or canon in seen:
                continue
            seen.add(canon)
            members = [i for i in range(r) if in_span(canon, rays[i])]
            slope = Fr(sum(deg[i] for i in members), k)
            desc = {"dim": k, "rays_in_V": [rays[i] for i in members],
                    "deg": sum(deg[i] for i in members),
                    "slope": [slope.numerator, slope.denominator]}
            if slope > worst[0]:
                worst = (slope, desc)
                top_canons = [canon]
            elif slope == worst[0]:
                top_canons.append(canon)
            if slope == mu:
                equalities.append(desc)

    if worst[0] > mu:
        verdict = "unstable"
        # The first Harder--Narasimhan term is the sum of all maximal-slope
        # subsheaves.  Form that sum explicitly so the stored witness is
        # canonical and independent of subspace-enumeration order.
        hn_dim, hn_canon = rref(
            [row for canon in top_canons for row in canon])
        hn_members = [i for i in range(r) if in_span(hn_canon, rays[i])]
        hn_deg = sum(deg[i] for i in hn_members)
        hn_slope = Fr(hn_deg, hn_dim)
        assert hn_dim < n and hn_slope == worst[0]
        assert all(all(in_span(hn_canon, row) for row in canon)
                   for canon in top_canons)
        worst = (hn_slope,
                 {"dim": hn_dim,
                  "rays_in_V": [rays[i] for i in hn_members],
                  "deg": hn_deg,
                  "slope": [hn_slope.numerator, hn_slope.denominator]})
    elif worst[0] == mu:
        verdict = "strictly semistable"
    else:
        verdict = "stable"

    return {
        "name": name,
        "dim": n,
        "num_rays": r,
        "degrees": deg,
        "anticanonical_degree": total,     # = (-K)^n
        "mu_TX": [mu.numerator, mu.denominator],
        "max_subsheaf_slope": [worst[0].numerator, worst[0].denominator],
        "witness": worst[1],
        "equality_witnesses": equalities,
        "verdict": verdict,
        "barycenter": [[b.numerator, b.denominator] for b in bary],
        "kahler_einstein": all(b == 0 for b in bary),
    }


# ---------------------------------------------------------------- validation set

VALIDATION = {
    # --- toric del Pezzo surfaces (all 5) ---
    "P2": [(1, 0), (0, 1), (-1, -1)],
    "P1xP1": [(1, 0), (-1, 0), (0, 1), (0, -1)],
    "dP1 (= F_1 = Bl_1 P2)": [(1, 0), (0, 1), (1, 1), (-1, -1)],
    "dP2 (= Bl_2 P2)": [(1, 0), (0, 1), (1, 1), (-1, 0), (-1, -1)],
    "dP3 (= Bl_3 P2)": [(1, 0), (0, 1), (1, 1), (-1, 0), (0, -1), (-1, -1)],
    # --- sample smooth toric Fano 3-folds ---
    "P3": [(1, 0, 0), (0, 1, 0), (0, 0, 1), (-1, -1, -1)],
    "P2xP1": [(1, 0, 0), (0, 1, 0), (-1, -1, 0), (0, 0, 1), (0, 0, -1)],
    "P1xP1xP1": [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0),
                 (0, 0, 1), (0, 0, -1)],
    "Bl_pt P3 (= P(O+O(1)) over P2)": [(1, 0, 0), (0, 1, 0), (0, 0, 1),
                                       (-1, -1, -1), (1, 1, 1)],
    "P(O+O(2)) over P2": [(1, 0, 0), (0, 1, 0), (-1, -1, 2),
                          (0, 0, 1), (0, 0, -1)],
    "P1xdP1": [(1, 0, 0), (0, 1, 0), (1, 1, 0), (-1, -1, 0),
               (0, 0, 1), (0, 0, -1)],
    # --- sample smooth toric Fano 4-folds (dim-4 code path validation) ---
    "P4": [(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1),
           (-1, -1, -1, -1)],
    "P2xP2": [(1, 0, 0, 0), (0, 1, 0, 0), (-1, -1, 0, 0),
              (0, 0, 1, 0), (0, 0, 0, 1), (0, 0, -1, -1)],
    "P1^4": [(1, 0, 0, 0), (-1, 0, 0, 0), (0, 1, 0, 0), (0, -1, 0, 0),
             (0, 0, 1, 0), (0, 0, -1, 0), (0, 0, 0, 1), (0, 0, 0, -1)],
    "Bl_pt P4": [(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1),
                 (-1, -1, -1, -1), (1, 1, 1, 1)],
}


def fmt_frac(pair):
    num, den = pair
    return str(num) if den == 1 else f"{num}/{den}"


def report(res):
    bary = "(" + ", ".join(fmt_frac(b) for b in res["barycenter"]) + ")"
    line = (f"{res['name']:<34} dim {res['dim']}  "
            f"(-K)^n = {res['anticanonical_degree']:>3}   "
            f"mu(T) = {fmt_frac(res['mu_TX']):>6}   "
            f"max mu(V) = {fmt_frac(res['max_subsheaf_slope']):>6}   "
            f"{res['verdict']:<20} "
            f"KE: {'yes' if res['kahler_einstein'] else 'no '}  bary = {bary}")
    print(line)


def main():
    results = []
    print("Tangent-bundle stability w.r.t. -K  (Klyachko slope check, exact)")
    print("=" * 130)
    for name, rays in VALIDATION.items():
        res = analyze([tuple(v) for v in rays], name)
        report(res)
        results.append(res)
    out = os.path.join(os.path.dirname(__file__), "..", "output",
                       "validation_verdicts.json")
    with open(out, "w") as f:
        json.dump(results, f, indent=1)
    print(f"\nwrote {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
